### ISSUE TITLE
Some "TODO" suggests, notes, recommendations, smells, etc

### ISSUE THREAD

**Issue by ghost** [cleverwise/cya#1]
https://github.com/terminalforlife/cya/blob/master/cya

Hi, shell lover here. I'm "Squidgy Testicle" on YT. Sorry for the weird name... lol I mentioned that I'd have a look at it.

I've forked the project and gone through the majority of cya itself, until my eyes were about to pop from tiredness. lol Plenty of feedback there, just look out for "#TODO - " in the text, using your editor's search feature. Will revisit tomorrow and follow through with some actual code and testing, but bit drained tonight.

Hope I can be or have been of some help!

**Comment by cleverwise** [comment]
You do raise some valid points, however some of your assumptions aren't quite correct.   Also there are security angles to consider.  For example it would confuse the user when to run sudo so they would always run sudo.  That isn't best practice.  Sudo should only be used when necessary.  Thus it is best to let the script call sudo when necessary.  After all why call sudo and execute with root privileges when just listing the backup profiles?

I will grant you looking for sudo true is probably a better idea.  I just slapped that in there and moved on with the other functions. :-)

Also I do realize curl isn't as widely installed however it is far safer than wget.  All security people I follow say never use wget period.  Curl is just more secure so I always use that solution.  The script could check for both but I default to security in my coding, when I know at least.

I know in some places the code could be tightened up.  :-)  Still at present everything works on multiple systems.

I can fork your file and add my own comments as some things will cause issues.

**Comment by cleverwise** [comment]
After reviewing the file in more detail I would rather not clone that in this project.  I don't want to confuse others downloading this utility.  If you could visit the cyberws.com website and click on contact link and select "Technical Consulting" I'll email you thoughts on your comments.  Thanks!

**Comment by ghost** [comment]
Oh nono, all I did was add TODOs -- I wasn't suggesting you just tack on the TODOs and call it a day. lol It wouldn't confuse them if you used a development branch. :) Then you could update master as needed. Seems to be the normal approach with GitHub.

I'll have a look at the site.

**Comment by cleverwise** [comment]
I really should look into using branches.  At this point I haven't used branches on github.  The contact was just so you could submit an email address.  :-)  All that is done via SSL from the site to the email server.  I do everything in SSL well TLS 1.2 high bit encryption.

**Comment by ghost** [comment]
Ooh. Not a worry, this is what I use for this sort of thing, so I don't mind publicly sharing it:

terminalforlife@yahoo.com

**Comment by cleverwise** [comment]
Okay I sent an email titled: "CYA Follow Up".   Thanks!

**Comment by cleverwise** [comment]
I noticed I missed a few comments last night so I sent email titled: "CYA Follow Up v2" with the updated file.  Sorry about that.

**Comment by cleverwise** [comment]
Any thoughts you wish to share?  You may also send a reply email.

**Comment by ghost** [comment]
No, you seem happy with it so I'll leave it there. Good luck.

**Comment by Lewiscowles1986** [comment]
> All security people I follow say never use wget period. Curl is just more secure so I always use that solution.

Do they give reasons?

**Comment by cleverwise** [comment]
Curl seems to be better at handling SSL/TLS connections.  That isn't to say wget can't do https but historically Curl has been stronger in this area.  In fact many programs rely on libcurl.  Curl also runs on more systems than wget and can be easily custom compiled.

The following doesn't matter for this application but are differences:

Curl has much better API support, which makes it a better choice for programming.  Curl also for two way communication which is great for data exchange.  Curl also supports a lot more protocols than wget.  Also Curl allows one to craft the structure of the call.  Now again these don't matter so much for CYA but there are advantages.

I personally avoid wget and never chose it over Curl.

**Comment by Lewiscowles1986** [comment]
Thanks, the original author of CURL mentions all those things [here](https://daniel.haxx.se/docs/curl-vs-wget.html). They are not security advantages, although switching between 11 SSL implementations is a testament to how well CURL is coded and how resilient it should be at coping with new security advisories if they affect specific implementations (like heartbleed did).

**Comment by cleverwise** [comment]
Well a lot of the security in all honesty is probably due to the fact Curl can be built against other SSL libraries.  OpenSSL, which is what most Linuxes use, is known to be very buggy and have issues.  That is why you have BoringSSL and other SSL libs.  Wget can't be built to use those unlike Curl.

In this specific case with cya wget is probably good enough.  Still, as stated, I just don't use wget.  I don't like it or trust it.  I trust Curl for its far better library support, more features, wider adoption, better API.

I also use Curl over wget at the command line when download files and things like that.  It is very easy to use and there is no advantage to wget over Curl.
