### ISSUE TITLE
cya mydata - expand / autocomplete profile names

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#10]
It would be "really" nice that the command `mydata` would expand / autocomplete the different profiles defined in the config file.

Following the example, in our config file
```
MYDATA_johnfiles="/home/john/ /mnt/wd-password/john/"
```

then

```
cya mydata [tab]
```

could result into 

```
cya mydata johnfiles
```

It would be really nice and useful in order to minimize spelling mistakes.

**Comment by cleverwise** [comment]
Well that would make things easier.  However it would also eliminate the safety check.  I'll look into this feature.

**Comment by cspaniard** [comment]
"safety checks" are strange, since us humans tend to go around them ;). If you have, let's say, 5 profiles (just a few).... more than likely you will end up getting the list with
```
$ grep -i mydata_ /home/cya/cya.conf
MYDATA_johnfiles="/home/john/ /mnt/wd-password/john/"
MYDATA_johnwd="/home/john/ /mnt/wd-password/john/"
MYDATA_johnnas="/home/john/ /nas/john/"
MYDATA_maryfiles="/home/mary/ /mnt/wd-password/mary/"
```

and then, copy & paste the name you are after... 

IMHO, this copy & paste and expanding automatically end up with the same result with the same "safety check"... is it really that dangerous from a human mistake point of view ?

Just a thought

**Comment by cleverwise** [comment]
That is how I was thinking of doing it.  A list function rather than tab.  I personally like listing the directories as that is the safety check rather than hitting tab to auto fill a profile.  It seems the list is a good blend of both.  :-)

**Comment by cspaniard** [comment]
Nice... maybe for sake of simplicity 
```
cya mydata [enter]
```
could return the list...

What do you think ?

**Comment by cleverwise** [comment]
Yeah that would work.

**Comment by cleverwise** [comment]
Okay 2.3.1+dev/2.4 will list available profile names.

**Comment by cspaniard** [comment]
My initial tests executing 

```cya mydata```

yields the result

```
☀ Cover Your Ass(ets) v2.3.1 ☀

ACTION ⯮ Backing Up Your User Data

{ERROR} No such backup profile

Available backup profiles:
---------------------------------------------
test1
david
```

Although technically true, the fact of not providing a profile was done on purpose to get the list.

Should I be getting an error message ?  In order to get the list, it is what I am supposed to do. Why the error?

I understand that if a profile was provided and it does not exist, the error should be displayed. However, no profile was provided in order to retrieve the list.

**Comment by cleverwise** [comment]
Fair enough.  I modified 2.3.2 to display "Please specify a backup profile" instead of an error.

**Comment by cspaniard** [comment]
Works as expected
