### ISSUE TITLE
missing exclude files from configfile documentation ?

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#13]
The following is the outline of the `configfile` documentation (I generated it with grep)

```
• Additional directories to include in backup:
• Exclude subdirectories from backup:
• Add specific files to include in backup:
• Alter number of rotation backups:
• Backup user data
• Turn off disclaimer notice:
```

There is a section I am missing (or not seeing)

```
Exclude files from backup:
```

The `directories` seems to show it can exclude individual files...

```
+++++++++++++++++++++++++++++++++++++++++++++
Excluded Sources:

Directories:
---------------------------------------------
/usr/bin/ ... skipping
/usr/src/ ... skipping
/var/backups/ ... skipping

Files:
---------------------------------------------
```

If my assumption is correct, I cannot find the documentation to write the proper config line(s).

**Comment by cleverwise** [comment]
You simply treat a file the same as a directory for notation.  That should tell rsync to ignore that file (although some more testing is needed)

EXCLUDE_/var/="log/syslog"

**Comment by cspaniard** [comment]
It makes sense, but shouldn't the documentation reflect that ?

It could very well be in the same section as "Exclude subdirectories from backup"... Maybe it could be renamed to "Exclude subdirectories/files from backup" and add a little clarification. Like the one you just gave... ;)

**Comment by cleverwise** [comment]
Yeah I added it to the list already. ;-)

The excluding files should have always worked as CYA just passes those entries to rsync using exclude and doesn't really care file or directory.

**Comment by cleverwise** [comment]
In v2.3.3

**Comment by cspaniard** [comment]
Excluding a directory seems to work. However, excluding a file does not.
``` cya.conf
[...]
EXCLUDE_/etc/="xml/ zsh_command_not_found"
[...]
```

Does not copy the `xml/` directory but it _does_ copy the `/etc/zsh_command_not_found` file.

**Comment by cleverwise** [comment]
Correct.  CYA was designed to exclude directories and not files.  Thus it runs a directory exists check before adding in excluded flag.  I have added a file check too in v2.3.5+

**Comment by cleverwise** [comment]
Actually this will take some more coding as I only fixed it in one spot.

**Comment by cleverwise** [comment]
This appears to be working 2.3.5+ but needs more testing.

**Comment by cspaniard** [comment]
It works -> Check OK
