### ISSUE TITLE
Inconsistent syntax dealing with root directory names with spaces

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#14]
In order to make root directories names with spaces work, I had to do the following

```
EXCLUDE_/directory\ with\ spaces/="test3/ with\\ spaces/"
```
As we can see when the root directory itself has spaces, we can only escape the space with a single `\`. However, when we need to declare a sub-directory, we need to use the `\\` in front of the white space.

This obviously inconsistent, but I don't if it has a solution. If it doesn't, maybe it should be documented.

**Comment by cleverwise** [comment]
Correct.
Technically \ is needed for the spaces which is set in the directory name for CYA itself.  However the double slash is needed for so \ gets passed to the command line.

**Comment by cspaniard** [comment]
That was my guess...

In order to avoid confusion, do you think that could be documented ?

**Comment by cleverwise** [comment]
Yeah I'll add it and let you know.  :-)

**Comment by cleverwise** [comment]
In 2.3.4

**Comment by cspaniard** [comment]
Checked -> OK
