### ISSUE TITLE
Avoid ambiguity in what forward slash we are referring to

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#15]
In the `configfile` command, "Exclude subdirectories from backup" section, we can find the following message

```NO FORWARD SLASHES FOR CHILDREN DIRECTORIES!```

in order to avoid ambiguity, maybe it could be changed to

```NO LEADING FORWARD SLASHES FOR CHILDREN DIRECTORIES!```

since we **do** need the trailing slash for children directories.

Just a thought...

**Comment by cleverwise** [comment]
Fair point.

**Comment by cleverwise** [comment]
In v2.3.3

**Comment by cspaniard** [comment]
Checked -> OK
