### ISSUE TITLE
Question: Changing cya HOME_DIR

### ISSUE THREAD

**Issue by incansvl** [cleverwise/cya#24]
I just downloaded cya and was looking at the installation instructions and how to configure it.

The cya home or working directory is /home/cya by default.

However my /home partition (actually a btrfs subvolume) contains only "real" user home directories and i'd like to keep it that way. I have a separate backup subvol (/share/backup) so I was considering moving the cya home to there

However, when I Iooked at the cya script to find where HOME_DIR is set, further down the script I noticed the following lines-

```
if [ ! -d "${HOME_DIR}" ]
then
        RECOVER_DIR="/mnt/cya/home/cya"
```

i'm really not a shellscript programmer, but this looks to me as if it effectively harcodes the value of HOME_DIR as /home/cya, because if I move HOME_DIR to- (say) /some/other/mount/point, and then later  mount that image under /mnt, wouldn't the lines above need to be-

```
if [ ! -d "${HOME_DIR}" ]
then
        RECOVER_DIR="/mnt/cya/some/other/mount/point/cya"
```
?

Maybe i'm mis-understanding this, but it looks to me as if the key line should look more like-

`        RECOVER_DIR="/mnt/cya${HOME_DIR}"
`

**Comment by cleverwise** [comment]
Correct.  The home directory is hardcoded for various reasons (a variable file was debated in the original design).  However you have some options:

1) You may change the HOME_DIR and RECOVER_DIR.  Of course you'll need to remember to change these variables on future updates.

2) You may use another storage device and set its mount point at /home/cya/ thus modifying the storage device for that directory.

**Comment by cleverwise** [comment]
As for the second part.  Correct.  You need to tell the script where you'll be mounting the block storage when booting off a live image.

**Comment by incansvl** [comment]
Hmm. I would normally like to see the configuration done outside the main script so it doesn't get overwritten by updates. The way I've typically seen that done is via environment variables set before the script runs, e.g. in root's `.profile.` This could be optional, so if the values aren't set in the environment the script uses the defaults.

I realise this potentially causes a "bootstrap" problem during a restore if the root profile is one of the things that was damaged, and the user was expecting a cya restore to fix it, but then presumably the same would apply to the custom mount point option if the fstab got damaged.

Ideas-

1. If the "generate restore script" function was run AFTER configuration, it could write any custom HOME_DIR and RECOVER_DIR locations out to the recovery script.
2. The recovery script could look for the environment variables and prompt for the values interactively in the (hopefully uncommon) circumstance where the environment values are missing when it is run.

**Comment by cleverwise** [comment]
The bootstrapping is exactly why a configuration file was skipped after much thought.

**Comment by incansvl** [comment]
This doesn't meet my needs, but I respect your view.

Annoyingly i've since tried TimeShift and that won't work for me either (it insists on storing backups in a root folder mounted on a raw device, but my backup folder is a subvolume so TS doesn't recognise it...)

I'd rather not roll my own solution because I suspect this is something that's very easy to get wrong, so I guess i'll have to keep looking.

Thanks for your replies.

**Comment by cleverwise** [comment]
I understand.  Out of curiousity what didn't work with CYA?
