### ISSUE TITLE
Last Run indicator

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#3]
Hello,

Would it be possible to add an asterisk (or something) next to the number to indicate more clearly which one is the last one? Example:
```
Backup Name                                    Date & Time
--------------------------------------------------------------------------------
1*                                             jue 14 dic 2017 21:55:20 CET
--------------------------------------------------------------------------------
2                                              jue 14 dic 2017 19:58:40 CET
--------------------------------------------------------------------------------
3                                              jue 14 dic 2017 19:58:40 CET
--------------------------------------------------------------------------------
```

I assume it could be done based on the file `LAST_RUN`

It could be a nice and helpful touch...

TIA,
David

**Comment by cleverwise** [comment]
Interesting idea.  Yup that wouldn't hard to do.

Asterisk works or perhaps some text (Last Run), (Last Used), (Most Recent)? Thoughts?

**Comment by cspaniard** [comment]
Here is an idea
```
Backup Name                                    Date & Time
--------------------------------------------------------------------------------
1  <--- Last Run                               jue 14 dic 2017 21:55:20 CET
--------------------------------------------------------------------------------
2                                              jue 14 dic 2017 19:58:40 CET
--------------------------------------------------------------------------------
3                                              jue 14 dic 2017 19:58:40 CET
--------------------------------------------------------------------------------
```
Since you already use fancy characters in the script, maybe you could a nice arrow character(s) instead of ASCII art.

Just an idea...

**Comment by cleverwise** [comment]
Nice.  I'll look into adding that soon.

**Comment by cleverwise** [comment]
I have a working prototype that has this feature.  Would you like to be added to credit section? If so how would you like to be listed?

**Comment by cspaniard** [comment]
Well... I am not sure...  my name suppose:

David Sanroma 

Thanks....

**Comment by cleverwise** [comment]
You got it!  I'll release v1.7 in the next few days with credit to you.
