### ISSUE TITLE
Bash Tab Completion

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#4]
Hi,

I am writing a bash completion script for `cya`. I am trying to make it somewhat "smart" in the sense of context. For example:

`cya keep [TAB]` would expand `name` because is part of `keep` and wait for the _name_ and then expand `overwrite` or  `archive` only
but 
`cya directories` would not expand `name` or anything for that matter.

I am having a hard time to get my head around all possible combinations and I wonder if you have them documented or written down somewhere.

Of course, if you like the end result you can have the script  ;)  and do anything you like with it. 

TIA,
David

**Comment by cleverwise** [comment]
Hello,

An interesting idea.  I will take a look at it when you are done. :-)  Thanks!

As for a list really help has them all short of the keep name INSERT_NAME (overwrite/archive)

> cya help

:-)

**Comment by cspaniard** [comment]
Hello,

Here is an initial test...

![cya_tab_opt](https://user-images.githubusercontent.com/5539214/34069960-58ffe144-e25b-11e7-8887-1be30643f36c.gif)

The context seems to work as it should... 

On the other hand, there are things like `cya restore` and `cya archive` where `cya` right now does not support passing the backup name as a parameter.

However, I think it might be a nice addition to do so. As you can see, the expansion script already supports it in case you decide to add it to `cya`. I think it flows very naturally and would be a nice touch, don't you ? ;)

Please, let me know what you think...
David

**Comment by cleverwise** [comment]
That looks really good.

As for restore and archive that was done on purpose.

> cya archive

Is designed more to walk you through the process.  For all command line that is what **keep name XYZ archive** is design to do.

As for restore that really should only be run in a live environment and I think best to list the current restore points.  Therefore passing the restore point name at the command line was intentionally omitted.

So those are the reasons behind those choices.  The rest looks really good!

**Comment by cspaniard** [comment]
Ok... I see...

Then I will remove the auto-complete of the back-up names.

If I understand correctly, the only context sensitive auto-completion should be in the `keep` command.
The rest, just complete the command with no more arguments or anything.

Is this correct ?

David

**Comment by cspaniard** [comment]
Hi...

It is done... At least done enough for you to try out ;)

How can I give you the script ?

David

**Comment by cleverwise** [comment]
Well all commands are case sensitive.

You may add files using this comment box as there is a link "selecting them".

**Comment by cspaniard** [comment]
Hi...

Here is the code...

I added the `.txt` extension because it would not let me upload it without a known extension, please remove it for testing... ;)

let me know what you think...
David


[cya_completion.txt](https://github.com/cleverwise/cya/files/1565167/cya_completion.txt)

**Comment by cleverwise** [comment]
Thanks!  I'll give it a test.  It might be a day or so but I'll get back to you soon.

**Comment by cleverwise** [comment]
This works great.  An awesome job!

**Comment by cspaniard** [comment]
Glad you like it ;)

I think it enhances `cya` and if you also think so... feel free to add it to the project if you like. Maybe you can put your same copyright / usage notice at the top, so it is consistent with `cya` script code.

Of if you like I can do it too... it is up to you... ;)

I am just very glad to help enhance `cya` since we are getting ready to put it into production at work.

Thanks,
David

**Comment by cleverwise** [comment]
I'll include this in stock cya with version 1.7.  Thank you! :-)

I, too, agree it does enhance cya.

That is awesome news about using it at work.  I have heard from several people that cya has saved them time and their systems.

I'll give you credit for the auto complete in the credits.  I should be able to get cya v1.7 out in the next few days.

**Comment by cspaniard** [comment]
Great!!! Thanks.... glad to help...

We are looking at implementing `cya` to backup our mission critical PBX system. No phones = No sales ;)

Right after that it will be our CentOS servers.

One question... From now on, will you maintain the Tab Completion Script ? or would you like me to keep on doing it under your coordination, and then send you pull requests to adopt the changes into the main branch ?

**Comment by cleverwise** [comment]
If you have additional ideas you are free to contact me however I'll add any new functions to the auto complete script.  I'll make this a supported feature starting in version 1.7.

**Comment by cspaniard** [comment]
Perfect!!! Will do ;) !!!

**Comment by cleverwise** [comment]
Okay I have released version 1.7 which covers this and the last run option.  Thanks!
