### ISSUE TITLE
Last Profile Used

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#5]
Hi... 

Glad to see the new version is out... great!!!

However, I tried to see the _last profile used_ enhancement but I couldn't. It displays the same info as ver 1.6

I ran a new back-up, but still not there...

I ran a `diff` on versions 1.6 and 1.7

```
4c4
< Cover Your Ass(ets) v1.6 on 16 November 2017
---
> Cover Your Ass(ets) v1.7 on 23 December 2017
23c23
< VERSION="1.6"
---
> VERSION="1.7"
1357,1358c1357,1359
< 	echo "Feedback:"
< 	echo "- Tom D."
---
> 	echo "Additional collaborators and testers:"
> 	echo "* David Sanroma (BASH auto completion & last save notation)"
> 	echo "* Tom D. (disclaimer modification)"
```

No code seems to be there to show the "Last Run" profile used.

I just copied `cya` to `~/bin`... is that correct / enough ?

Just FYI...

TIA,
David

**Comment by cleverwise** [comment]
I know what happened.  That was my error.  I failed to copy that block of code back into the github upload version.  Thanks for catching that.  I'll just release v1.8 to fix that issue.

Sorry about that!  I'll do that today.

**Comment by cleverwise** [comment]
Okay fixed!  I just needed to copy that block of code from one my dev VM's.

Thanks again for the catch!

You are correct in that you just copy cya into your ~/bin/ and should be good to go.

**Comment by cspaniard** [comment]
Hi... glad to help... ;)

I downloaded and tested ver 1.8 and it shows last run as expected... 

Great job!!!

David
