### ISSUE TITLE
rsync unexpected behavior

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#6]
Hi...

I discovered that `rsync` is not behaving like I expected. In addition that makes `cya` show backup results that are surprising.

I ended up typing this on the CLI

```
sudo rsync -a --delete --exclude=systemd/ --exclude=cron.d/ /etc/ /home/cya/points/2/etc/
```

From previous runs `cya` already put `systemd` and `crond` directories there (when I had no exclusions). However, since `rsync` skips them completely, it does not delete them on destination, even if we have `--delete` option.

The result is that I ended up with a backup that I did not expect to have `systemd` nor `crond` directories, but there they were (from a previous run).

As I said, I think that it is an `rsync` weirdness...

Right now I can only think on deleting (`rm -fr`) the excluded directory/file before invoking the `rsync` command. Just and idea... ;)

I hope you can reproduce the results I have seen... ;)
David

**Comment by cspaniard** [comment]
Hi...

Looking around I just discovered `--delete-excluded` option.  I did not know it existed.

It seems "fix" the behavior mentioned earlier, yielding more predictable results.

I hope it helps ;)
David

**Comment by cleverwise** [comment]
Right.  That is how cya currently calls rsync.

Those excluded directories will **not** be restored.  So while they'll take up space it doesn't hurt to have them.  This can also happen if you include custom directories then remove them from the list or if you lower the max saves number.

So again while the files could still be there cya restore reads the exclusions and custom directories and will skip directories as necessary.  I am not against keeping things cleaner but I also didn't want cya just randomly deleting directories either.

It would have required a lot more logic to figure out what was safe to delete say when removing custom directories, lowering the save count, etc.

**Comment by cleverwise** [comment]
Well you know that **isn't** quite right on restoring the files from a directory.

The max saves and custom directories part **is correct**.  However if say you have /opt/ and you want to omit /opt/logs/ that was already been included in restore I didn't program cya to do that.

I tell you want I'll just release v1.9 with that --delete-excluded flag.  That is just the best way to handle that situation. :-)

**Comment by cspaniard** [comment]
I am with you... ;)

From a "newbie" perspective, it seems to be more clear to have a snapshot of only what you back up. For instance, I remember the video Mr. Server & Mr. Desktop. You and Joe mentioned the advantage of not needing the original application to be able to access the back-up files. That was one of the strong points of `cya`. The end result was just files you could get back directly.

IMHO, I think that having extra directories that you excluded could make things harder to restore by hand if you needed to, which is one strong point in favor of `cya` backups.

My English is just OK, but I think you know what I mean ;) 

Since you are the boss, it is up to you to balance all this out... hehehe ;)

David
PS: Merry Christmas

**Comment by cleverwise** [comment]
I have a working prototype that uses the delete-excluded flag if exclusions are included otherwise delete is used.

**Comment by cspaniard** [comment]
That sounds very interesting...

Would that be only save ? 

To do so on Restore could be dangerous, couldn't it ? I am not sure how cya handles Restores right now with excludes.

**Comment by cleverwise** [comment]
This is only on saving (any method) however on restore --delete is used if turned on.

**Comment by cspaniard** [comment]
That makes total sense...

Looking forward to checking 1.9 out... ;)

**Comment by cleverwise** [comment]
Okay I've been doing some coding, as time as permitted.

I must say I was first right then wrong about the restore.  It takes a bit to get back into all the code as going from one project to another I don't remember everything off the top of my head.

At any rate the restore via CYA does skip excluded directories.  If you look around line 608 you'll see the exclude logic for restores.  So I already addressed that issue.  Still using --delete-excluded is a good idea.  I'm planning on just leaving that excluded code for restore/recovery as it shouldn't hurt anything; at least for now.

I am also building in a way to backup personal data although for v1.9 that will be a hidden function until a future version.

If you want to visit cyberws.com and go to the contact form then send me your email, unless you want it being public, I'll send you a test copy of 1.9 to see how excluded is working.

Thanks.

**Comment by cleverwise** [comment]
Email sent just in case spam/junk filter got it.

**Comment by cleverwise** [comment]
Version 2.0 with the additions we mentioned has been released.  Plus cya_completion was updated for mydata.
