### ISSUE TITLE
How to specify to exclude a root level directory

### ISSUE THREAD

**Issue by cspaniard** [cleverwise/cya#9]
In the config file we can exclude 2nd level directories and downwards with the syntax
```
EXCLUDE_/usr/="games/"
```

However how can we exclude a 1st level directory... ? Let's say we want to exclude `/usr/` entirely

What would be the syntax then ?

I think I tried this in an earlier version and I think it did not work... maybe I am wrong...

```
EXCLUDE_//="usr/"
```

TIA

**Comment by cleverwise** [comment]
This would need to be added.  You are correct CYA won't skip a whole top level directory.  It was originally designed to backup all top level system directories.

However something like the following could be added:

EXCLUDE_/usr/="CYA_SKIP_DIRECTORY"

I would want to make sure the odds of a name collusion would be basically nill.

**Comment by cspaniard** [comment]
What about `EXCLUDE_/usr/=""` ?

No name collision at all ;)

In addition, it is very consistent with the syntax in place now.

**Comment by cleverwise** [comment]
I thought of that too but typing something in would be a better opt out in case some user starts that and forgets to go back and enter something.  CYA_SKIP or something means you are really sure you don't want the directory backed up.  It just seems a "safer" way to confirm this action.

**Comment by cleverwise** [comment]
This is now in 2.3.3 and works differently.  Instead of opting out CYA now allows to override the default backup list.

OVERRIDE_BACKUP_DIRECTORIES=""

Is used to create your own list.

**Comment by cspaniard** [comment]
The documentation section `• Removing/Altering default top level backup directories` 
tells us that with the `cya directories` command we can get a list of default top directories that will be backed-up. However, I don't get such list.

On the other hand, if I specify `OVERRIDE_BACKUP_DIRECTORIES` it does show the list for this setting.

Any ideas ?

**Comment by cleverwise** [comment]
Confirmed bug.  Fixed in v2.3.5+

**Comment by cspaniard** [comment]
Checked OK
